AllCops:
  Exclude:
    - spec/dummy/bin/**/*
    - spec/dummy/config/**/*
    - spec/dummy/Rakefile
    - tmp/**/*

LineLength:
  Description: Limit lines to 120 characters, which is what github can display.
  Max: 120

ExtraSpacing:
  Description: Sometimes it's ok to line up some things for readability -- though it's bad for diffs.
  Enabled: false

UnneededPercentX:
  Description: It's easier to search for %x than it is to search for `.
  Enabled: false
