source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec name: "teaspoon-jasmine", path: "../../teaspoon-jasmine"
gemspec name: "teaspoon-devkit", path: "../.."
